# 1 Elasticsearch node, 1 Kibana instance with xpack security enabled (Basic Licence) - (v7.2.0)
# Based on https://github.com/glenacota/elastic-training-repo/blob/master/clusters-to-go/7.2.0/1es-1kibana.yml

# example settings are here https://github.com/elastic/elasticsearch/blob/master/distribution/docker/docker-compose.yml

#
# the underlying host/vm needs this config setting or ES nodes will not boot fully
#   with a bootstrap failure
#
# myhostmachine$ sudo sysctl -w vm.max_map_count=262144
#

# test all ok with  curl http://localhost:9200/_cluster/health?pretty


version: '3'
services:
  esnode:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: esnode
    environment:
      - node.name=esnode
      - node.attr.location=central
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=Password01
      - path.repo=/tmp
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Password01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elastic-net
    links:
      - esnode:elasticsearch

volumes:
  esnode-data:
    driver: local

networks:
  elastic-net:
